export const CallEvent = {
  SEND_CALL_INVITE: 'SEND_CALL_INVITE',
  RECEIVE_CALL_INVITE: 'RECEIVE_CALL_INVITE',

  ACCEPT_CALL_INVITE: 'ACCEPT_CALL_INVITE',
  DECLINE_CALL_INVITE: 'DECLINE_CALL_INVITE',

  START_CALL: 'START_CALL',
  END_CALL: 'END_CALL',

  UPDATE_ICE_CANDIDATE: 'UPDATE_ICE_CANDIDATE',
  UPDATE_SESSION_DESCRIPTION: 'UPDATE_SESSION_DESCRIPTION',

  SERVER_EXCEPTION: 'SERVER_EXCEPTION',
};

export const CallActor = {
  SENDER: 'sender',
  RECEIVER: 'receiver',
};
